import sys

sys.stdout.write(f"220 COMP 431 FTP server ready.\r\n")
sys.stdout.write(f"USER anonymous\r\n")
sys.stdout.write(f"331 Guest access OK, send password.\r\n")
sys.stdout.write(f"PASS foobar\r\n")
sys.stdout.write(f"230 Guest login OK.\r\n")
sys.stdout.write(f"syST\r\n")
sys.stdout.write(f"215 UNIX Type: L8.\r\n")
sys.stdout.write(f"type I\r\n")
sys.stdout.write(f"200 Type set to I.\r\n")
sys.stdout.write(f"NOOP\r\n")
sys.stdout.write(f"200 Command OK.\r\n")
sys.stdout.write(f"PORT 152,2,131,205,31,144\r\n")
sys.stdout.write(f"200 Port command successful (152.2.131.205,8080).\r\n")
sys.stdout.write(f"RETR MakeOutput1.py\r\n")
sys.stdout.write(f"150 File status okay.\r\n")
sys.stdout.write(f"250 Requested file action completed.\r\n")
sys.stdout.write(f"QUIT\r\n")
sys.stdout.write(f"200 Command OK.\r\n")
